name: CI
on:
  push:
    branches:
      - "main"

jobs:
  Check-Python-Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'
          cache: 'pip'

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Check python types
        run: yarn pyright

      - name: Lint files
        run: pylint **/*.py