name: CI
on:
  push:
    branches:
      - "main"

jobs:
  Check-Python-Types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install python dependencies
        run: pip3 install --user -r requirements.txt

      - name: Check python types
        run: yarn pyright